import { defineConfig } from "vitest/config";
import vue from "@vitejs/plugin-vue";
import { quasar, transformAssetUrls } from "@quasar/vite-plugin";
import jsconfigPaths from "./vitest-jsconfig-paths";
import path from "path";
import { nodePolyfills } from "vite-plugin-node-polyfills";

export default defineConfig({
  build: {
    target: "esnext",
  },
  optimizeDeps: {
    esbuildOptions: {
      target: "esnext",
    },
  },
  test: {
    globals: true,
    environment: "jsdom",
    fileParallelism: false,
    threads: false,
    singleThread: true,
    setupFiles: ["./test/vitest/setup-file.js"],
    include: [
      "test/vitest/__tests__/buckets.spec.ts",
      "test/vitest/__tests__/creators-tiers.spec.ts",
      "test/vitest/__tests__/CreatorStudioPage.publish.spec.ts",
      "test/vitest/__tests__/creatorCard.discovery.spec.ts",
      "test/vitest/__tests__/donationPrompt.spec.ts",
      "test/vitest/__tests__/TierSummaryCard.spec.ts",
      "test/vitest/__tests__/cashu.stores.spec.ts",
      "test/vitest/__tests__/welcome.interaction.spec.ts",
      "test/creatorStudio/tierComposerUtils.spec.ts",
      "test/creatorStudio/TierComposer.interaction.spec.ts",
      "test/cashu-sendQueue.spec.ts",
      "test/encryptNip04.spec.ts",
      "test/dexie-migrations.spec.ts",
      "test/MediaPreview.sanitize.spec.ts",
      "test/lib/fundstrApi.spec.ts",
      "test/api/fundstrDiscovery.spec.ts",
      "test/utils/core-helpers.spec.ts",
      "test/utils/app-helpers.spec.ts",
      "test/utils/wallet-helpers.spec.ts",
      "src/js/__tests__/nutzapProfile.test.ts",
      "test/mints.store.spec.ts",
      "test/stores/mints.balance.spec.ts",
      "test/stores/proofs.store.spec.ts",
      "test/stores/fetchFundstrProfileBundle.spec.ts",
      "test/invoiceHistory.store.spec.ts",
      "test/settings.store.spec.ts",
      "test/mnemonic.store.spec.ts",
      "test/restore.store.spec.ts",
      "test/stores/sendTokensStore.spec.ts",
      "test/stores/npubcash.store.spec.ts",
      "test/stores/tokens.store.spec.ts",
      "test/stores/receiveTokensStore.store.spec.ts",
      "test/stores/nwc.store.spec.ts",
      "test/stores/ndkBoot.store.spec.ts",
      "test/stores/lockedTokensDexie.store.spec.ts",
      "test/stores/nostr.signers.spec.ts",
      "test/stores/signer.store.spec.ts",
      "test/vitest/composables/useNostrAuth.spec.ts",
      "test/vitest/composables/useNostrProfiles.spec.ts",
      "test/vitest/composables/useCreatorHub.spec.ts",
      "test/vitest/composables/useNdk.spec.ts",
      "test/SendDialog.interaction.spec.ts",
      "test/SendTokenDialog.interaction.spec.ts",
      "test/AddMintDialog.interaction.spec.ts",
      "test/ReceiveDialog.interaction.spec.ts",
      "test/PayInvoiceDialog.interaction.spec.ts",
      "test/ReceiveTokenDialog.interaction.spec.ts",
      "test/message-input.interaction.spec.ts",
      "test/message-list.behavior.spec.ts",
      "test/conversation-list.behavior.spec.ts",
      "test/components/BalanceView.behavior.spec.ts",
      "test/components/LoginPanel.interaction.spec.ts",
      "test/components/HistoryTable.behavior.spec.ts",
      "test/components/NostrSetupWizard.interaction.spec.ts",
      "test/components/NostrIdentityManager.interaction.spec.ts",
      "test/components/InvoicesTable.behavior.spec.ts",
      "test/components/TokenCarousel.behavior.spec.ts",
      "test/components/TierCard.behavior.spec.ts",
      "test/composables/useClipboard.spec.ts",
      "test/composables/useP2pkDiagnostics.spec.ts",
      "test/composables/usePwaInstall.spec.ts",
      "test/stores/payment-request.store.spec.ts",
      "test/wallet-store.spec.ts",
      "test/wallet-store.decodeRequest.spec.ts",
      "test/wallet-store.handleBolt11Invoice.spec.ts",
      "test/pages/WalletPage.spec.ts",
      "test/pages/NostrMessenger.spec.ts",
      "test/pages/Settings.spec.ts",
      "test/pages/Restore.spec.ts",
      "test/pages/TierComposer.interaction.spec.ts",
      "test/nostr/builders.spec.ts",
      "test/nostr/signer.spec.ts",
      "test/nostr/readBackAndFallback.spec.ts",
      "test/nostr/publishNostrEvent.spec.ts",
      "test/boot/**/*.spec.ts",
    ],
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
      src: path.resolve(__dirname, "src"),
      app: path.resolve(__dirname),
      components: path.resolve(__dirname, "src/components"),
      layouts: path.resolve(__dirname, "src/layouts"),
      pages: path.resolve(__dirname, "src/pages"),
      assets: path.resolve(__dirname, "src/assets"),
      boot: path.resolve(__dirname, "src/boot"),
      stores: path.resolve(__dirname, "src/stores"),
      "@cashu/cashu-ts": path.resolve(
        __dirname,
        "src/lib/cashu-ts/src/index.ts",
      ),
      "@noble/ciphers/aes.js": path.resolve(__dirname, "test/mocks/aes.js"),
    },
  },
  plugins: [
    vue({
      template: { transformAssetUrls },
    }),
    quasar({
      sassVariables: "src/quasar-variables.scss",
    }),
    jsconfigPaths(),
    nodePolyfills(),
  ],
});
